"""marke simulation

Revision ID: 4dec04fdc2f6
Revises: bad7f5c3cdc6
Create Date: 2026-05-05 10:51:20.930972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dec04fdc2f6'
down_revision: Union[str, None] = 'bad7f5c3cdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
