"""add stop_loss and target_price to positions

Revision ID: 5aaac3489350
Revises: 81961d457f1c
Create Date: 2026-05-05 12:53:01.282008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aaac3489350'
down_revision: Union[str, None] = '81961d457f1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('stop_loss', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('positions', sa.Column('target_price', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'target_price')
    op.drop_column('positions', 'stop_loss')
    # ### end Alembic commands ###
