"""add wallet tables changes

Revision ID: 8ad24aca6c0d
Revises: a9e014e39bba
Create Date: 2026-05-04 20:14:20.774618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ad24aca6c0d'
down_revision: Union[str, None] = 'a9e014e39bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
