"""added multi limit order 

Revision ID: 965cf85f5ddb
Revises: 5587bb6b8f69
Create Date: 2026-05-05 18:05:11.332127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965cf85f5ddb'
down_revision: Union[str, None] = '5587bb6b8f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
