"""add new change to wallet fix

Revision ID: bad7f5c3cdc6
Revises: 8ad24aca6c0d
Create Date: 2026-05-04 20:17:38.194125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bad7f5c3cdc6'
down_revision: Union[str, None] = '8ad24aca6c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
